trade:
  okx:
    api: https://www.okx.com
    wsPublicUrl: wss://ws.okx.com:8443/ws/v5/public
    wsPrivateUrl: wss://ws.okx.com:8443/ws/v5/private
    apiKey:
    secret:
    passphrase:
  bnb:
    api:
    wsPublicUrl:
    wsPrivateUrl:
    apiKey:
    secert:
    passphrase:
