spring:
  profiles:
    active: shadow, ${trade.exchange}
  main:
    web-application-type: none

logging:
  level:
    root: info

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    salt-generator-classname: org.jasypt.salt.ZeroSaltGenerator

websocket:
  reconnectTime: 10

trade:
  exchange: okx
  inst: BTC
  currency: USDT
  instType: SWAP
  instId: ${trade.inst}-${trade.currency}-${trade.instType}
  tdMode: isolated
  lever: 60
  stopFile: /opt/trading/stop-shadow
  longFile: /opt/trading/side-long
  shortFile: /opt/trading/side-short

  order:
    faceValue: 0.01
    firstContractSize: 1
    contractIncrementRate: 2
    maxOrder: 6
    extraMargin: 0
    followRates:
      - 0.006
      - 0.012
      - 0.018
      - 0.024
      - 0.030
      - 0.032
    pullbackRates:
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.003
    makerFeeRate: 0.0005
    takerFeeRate: 0.0002

  notify:
    windows: false
    robot: true
    webhook:
    secret:
    rateLimited: 20
    limitedPeriod: 60000
