spring:
  profiles:
    active: test, ${trade.exchange}
  main:
    web-application-type: none

logging:
  level:
    root: debug

websocket:
  reconnectTime: 5

trade:
  exchange: okx
  currency: USDT
  instId: BTC-${trade.currency}-SWAP
  tdMode: isolated
  lever: 50

  notify:
    windows: false
    robot: false
    webhook:
    secret:
