spring:
  profiles:
    active: test, ${trade.exchange}
  main:
    web-application-type: none

logging:
  level:
    root: debug

websocket:
  reconnectTime: 5

trade:
  exchange: okx
  inst: BTC
  currency: USDT
  instType: SWAP
  instId: ${trade.inst}-${trade.currency}-${trade.instType}
  tdMode: isolated
  lever: 50

  notify:
    windows: false
    robot: false
    webhook:
    secret:
