spring:
  profiles:
    active: shadow, ${trade.exchange}
  main:
    web-application-type: none

logging:
  level:
    root: info

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    salt-generator-classname: org.jasypt.salt.ZeroSaltGenerator

websocket:
  reconnectTime: 10

trade:
  exchange: okx
  inst: BTC
  currency: USDT
  instType: SWAP
  instId: ${trade.inst}-${trade.currency}-${trade.instType}
  tdMode: isolated
  lever: 60
  stopFile: /opt/trading/stop-shadow

  order:
    faceValue: 0.001
    firstContractSize: 10
    contractIncrementRate: 2
    maxOrder: 8
    extraMargin: 50
    followRates:
      - 0.006
      - 0.012
      - 0.018
      - 0.024
      - 0.030
      - 0.036
      - 0.042
      - 0.048
    pullbackRates:
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.006
      - 0.006
    makerFeeRate: 0.0005
    takerFeeRate: 0.0002

  notify:
    windows: false
    robot: false
    webhook: ENC(BDVXdsxuy1juYOmrgs+aKCv1A7URLxWTbnuS1BJQxVnYr6PM0f5xEZBX9uMmPZorMEKjag5Mr8TNCBYK9qx5uAxwVgvC03iN+SBIAxGgEAIy3CVJGoejhVrke7XnZ8c1iQNZ5TvzALfOZo0HBbhqSZ4SMyTYOxPg)
    secret: ENC(gD2ZslB+WiWhqgobxGZzB62tbFMnRS35vk7EQrmUh5Put34ofM2OzlaqaNurLwiXvKZpv8KOBP3Zd7amMWwybDjC+zjj6xxU)
    rateLimited: 20
    limitedPeriod: 60000
